entryPoints:
  web:
    address: ":80"
  websecure:
    address: ":443"
  legacy_absent:
    address: ":1473"
  legacy_kanjitest:
    address: ":9473"

providers:
  docker:
    exposedByDefault: false

certificatesResolvers:
  letsencrypt:
    acme:
      email: it@calgaryhoshuko.org
      storage: /letsencrypt/acme.json
      httpChallenge:
        entryPoint: web